# roles/redis/tasks/main.yml

---
- name: Install Redis
  apt:
    name: redis-server
    state: present
    update_cache: yes

- name: Configure Redis
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
  notify:
    - Restart Redis

- name: Ensure Redis is enabled and started
  systemd:
    name: redis-server
    state: started
    enabled: yes
