---
# roles/database/tasks/main.yml

- name: Make database migrations
  become_user: "{{ new_user }}"
  command: "/home/{{ new_user }}/.pyenv/versions/{{ venv_name }}/bin/python3 {{ remote_project_path }}/_base/manage.py makemigrations"

- name: Apply database migrations
  become_user: "{{ new_user }}"
  command: "/home/{{ new_user }}/.pyenv/versions/{{ venv_name }}/bin/python3 {{ remote_project_path }}/_base/manage.py migrate"
